"""add_report_style

Revision ID: d9da5596158c
Revises: b2caf40f9df1
Create Date: 2026-04-11 21:15:50.662982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9da5596158c'
down_revision: Union[str, None] = 'b2caf40f9df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT NULL without default fails when research_runs already has rows.
    # Add with server_default, then drop server default (app uses default="general").
    op.add_column(
        "research_runs",
        sa.Column(
            "report_style",
            sa.String(length=50),
            nullable=False,
            server_default=sa.text("'general'"),
        ),
    )
    op.alter_column("research_runs", "report_style", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_runs', 'report_style')
    # ### end Alembic commands ###
